<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\dotnet\options-pattern\Configuration.csproj" />
    <ProjectReference Include="..\..\dotnet\jwt-authentication\JwtAuthentication.csproj" />
    <ProjectReference Include="..\..\dotnet\transactional-email\SendingEmail.csproj" />
    <ProjectReference Include="..\..\dotnet\memory-caching\MemoryCaching.csproj" />
    <ProjectReference Include="..\..\dotnet\async-concurrency\AsyncConcurrency.csproj" />
    <ProjectReference Include="..\..\dotnet\json-serialization\JsonSerialization.csproj" />
    <ProjectReference Include="..\..\data\linq-internals\LinqInternals.csproj" />
    <ProjectReference Include="..\..\azure\docker-container-apps\DockerContainerApps.csproj" />
  </ItemGroup>

</Project>
